apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  namespace: cassandra
  name: cassandra-b
  annotations:
    apps.open-cluster-management.io/git-path: site-b/cassandra-b
    apps.open-cluster-management.io/git-branch: main
  labels:
    app: cassandra-b
spec:
  channel: cassandra/cassandra-app-latest-b
  placement:
    placementRef:
      name: cassandra-b
      kind: PlacementRule
