apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra
spec:
  clusterIP: None
  ports:
    - port: 9042
  selector:
    app: cassandra
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra-a-0
  name: cassandra-a-0
spec:
  clusterIP: None
  ports:
    - port: 7000
  selector:
    name: cassandra-a-0
