---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  namespace: cassandra
  name: cassandra
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: cassandra
  labels:
    app: cassandra
spec:
  channel: cassandra-app-latest
  placement:
    placementRef:
      name: cassandra
      kind: PlacementRule
