apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  namespace: cassandra
  name: cassandra
  annotations:
    apps.open-cluster-management.io/git-path: template/cassandra
  labels:
    app: cassandra
spec:
  channel: template/cassandra
  placement:
    placementRef:
      name: cassandra
      kind: PlacementRule
